default:
  target: Local_pg_db
  outputs:
    Local_pg_db:
      type: postgres
      host: localhost
      port: <YOUR_DATABASE_PORT>
      user: <YOUR_DATABASE_USER>
      password: <YOUR_DATABASE_PASSWORD>
      database: <YOUR_DATABASE_NAME>
